*MAT_USER_DEFINED_MATERIAL_MODELS_TITLE
UMAT43 - hyperelastic neo-Hookean material model using tensor toolbox ttb
$#     mid        ro        mt       lmc       nhv    iortho     ibulk        ig
         1   7.85e-6        45         8         0         0         3         4
$#   ivect     ifail    itherm    ihyper      ieos      lmca    unused    unused
         0         0         0         1         0         0
$#      p1        p2        p3        p4        p5        p6        p7        p8
$YoungsMod  PoissonR   bulkMod  shearMod
       207       0.3     171.5 79.153846
